rethinkdb:
  image: rethinkdb
  ports:
    - "9999:8080"
    - "28015"
  volumes_from:
    - rethinkdb-data

rethinkdb-data:
  image: rethinkdb
  volumes:
    - /data
  command: "true"

bigchaindb:
  build: .
  volumes:
    - ./:/usr/src/app/
    - ~/.bigchaindb_docker:/root/.bigchaindb_docker
  links:
    - rethinkdb
  environment:
    BIGCHAIN_DATABASE_HOST: rethinkdb
  command: bigchaindb -c /root/.bigchaindb_docker/config start
